####################################
######## HYPRLAND Yumei-Dev ########
####################################

###########################
######## AUTOSTART ########
###########################
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = dunst
exec-once = flameshot
exec-once = discord 
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

###########################
######## DARKMODE  #########
###########################
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
env = QT_QPA_PLATFORMTHEME,qt6ct

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

cursor {
    no_hardware_cursors = true
}

monitor=HDMI-1,preferred,auto,1

general {
    gaps_in = 5
    gaps_out = 3
    border_size = 2
    col.active_border = rgb(0f3460)
    col.inactive_border = rgb(45475a)
}

decoration {
    rounding = 12
    active_opacity = 0.90
    inactive_opacity = 0.80

    blur {
        enabled = true
        size = 8
        passes = 3
    }

    screen_shader = ~/.config/hypr/shaders/vibrance.glsl
}

# KEYBOARD LANGUAGE
input {
    kb_layout = latam
    kb_variant =
}

# STANDARD EXECUTABLES
$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher

###########################
######## KEYBINDS #########
###########################

# ESSENTIAL KEYBINDS
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, Escape, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Space, togglefloating
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, B, exec, zen-browser
bind = , Print, exec, flameshot gui
bind = $mainMod SHIFT, R, exec, killall waybar && waybar

# AUDIO & MEDIA KEYS
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute, exec, wpctl set-source-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous

# SWITCH WINDOW FOCUS USING THE ARROW KEYS
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# CHANGE WORKSPACE
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# MOVE WORKSPACES WINDOWS
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Window resizing and moving
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
